### ISSUE TITLE
Error when instantiating MessageType

### ISSUE THREAD

**Issue by Nokitoo** [Wizcorp/megadata#19]
When I try to create a message without using the `MessageType.create` method, it throws me an error when I use the method `MessageType.pack`.

Here is my code:
```javascript
// app.js
const message: JoinMessage = new JoinMessage();
message.nickname = 'Nokito';

message.pack(); // <= Throw an error


// messages/types/Join.js
import { Type, TypeIds } from '../'
import MessageType from 'megadata/classes/MessageType'
import JsonFormat from 'megadata/classes/JsonSerializationFormat'

@Type(TypeIds.Join, JsonFormat)
export default class JoinMessage extends MessageType {
  public nickname: string
}
```
And the error:

> JsonSerializationFormat.ts:23 Uncaught TypeError: Cannot read property 'setUint8' of undefined
>     at JoinMessage._pack (JsonSerializationFormat.ts:23)
>     at JoinMessage.../../../megadata/src/classes/MessageType.ts.MessageType.pack (MessageType.ts:113)
>     at MyRPCClient.<anonymous> (app.ts:13)
>     at MyRPCClient.../../node_modules/node-libs-browser/node_modules/events/events.js.EventEmitter.emit (events.js:78)
>     at WebSocket.<anonymous> (index.ts:55)

We could throw an Error when trying to instantiate a MessageType without using the `.create` method.

**Comment by stelcheck** [comment]
I'll fix this, but normally you should be using `MessageType.claim` to re-use objects from the object pool instead.
