### ISSUE TITLE
Strict mode error

### ISSUE THREAD

**Issue by yovanoc** [Wizcorp/megadata#41]
Hello! I wanna ask if this project is still under development or not?

Otherwise I try to going back in building my example project for megadata. I'm using a monorepo with lerna with the core, server, client, the protocol, and an api with graphql, it's super smooth but i've only problem with megadata... I don't know why it is spawning me this error :

`../../node_modules/megadata/lib/classes/MessageType.d.ts(30,63): error TS2344: Type 'keyof T' does not satisfy the constraint 'string'.
  Type 'string | number | symbol' is not assignable to type 'string'.
    Type 'number' is not assignable to type 'string'.`

**Comment by stelcheck** [comment]
Haven't been using it much, but I still maintain it when I can, and when issues arise. 

Issue should now be fixed.

**Comment by yovanoc** [comment]
Thanks! I will help you too when I can and i will show you the example project very soon :)

**Comment by stelcheck** [comment]
Damn :) looking forward!

**Comment by yovanoc** [comment]
Can you publish it to npm i can't see it?

**Comment by stelcheck** [comment]
CI is running and should deploy shortly. If it doesn't I'll deploy by hand.

We've implemented semantic releases, so normally, if all goes well, deploys should happen on every PR merges... might need fixing, however.

**Comment by stelcheck** [comment]
Should be up now.

**Comment by yovanoc** [comment]
yes good! see you soon :)
